### PR TITLE
Fix typo in Quickstart doc

### PR DESCRIPTION
**Pull request by nathanjmcdougall**

### CODE REVIEW

**Comment by dapper91** [comment]
@nathanjmcdougall Hi. Thank you for your contribution. Please change the target branch from master to dev.

**Comment by nathanjmcdougall** [comment]
Done, thanks.

**Comment by dapper91** [comment]
@nathanjmcdougall Hi. I think you are still branched from master. Please, rebase to dev.

**Comment by nathanjmcdougall** [comment]
I'm going to open a separate PR with `dev` as the base.

**Pull request closed without merging**
